### ISSUE TITLE
Ability to update mru list when entering a buffer

### ISSUE THREAD

**Issue by dylan-chong** [tweekmonster/fzf-filemru#10]
I'm not actually sure about whether this is a good idea or not, but I was thinking that we never a buffer is entered and/or created (that has a filename), they MRU list should be updated so the current file we will be at the start of the list.

The reason for this is that I may not open a file using fzf. For example I may open a file using nerd tree, which I would not be considering when a close the file and realise I want to reopen it. When a close one of them, I want to be able to use fzf mru to reopen it.

Another reason to consider is that I may open Vim from a session, which opens many files at once, neither of them from fzf. When a close one of them, just like the above, I want to be able to use fzf mru to reopen it.

What do other people think of this idea?

**Comment by tweekmonster** [comment]
When I was first developing this, I wanted it to be along the same lines of what you're describing.  The problem I saw is that it made it take much longer for infrequently used files to naturally age, especially in cases where sessions are used.  The other problem is that it's impossible to know _how_ a buffer was loaded.

Without knowing how a buffer is loaded, the MRU list could be updated much more frequently than expected.  Imagine that you have a project where you have ~10 files you reference frequently, but don't actually edit.  With the default settings, FZF will open with about 10 visible lines.  Your reference files will most likely never move from the top 10 positions.  While FZF does offer an excellent UI for filtering this list, you will be forced to filter the list to find something other than your reference files.  IMO, that defeats one of the key benefits of having an MRU list with FZF: less typing.

In any case, I made the `UpdateMru` command available to you so that you can update the MRU as you see fit.  Example usage:

```vim
augroup custom_filemru
  autocmd!
  autocmd BufWinEnter * UpdateMru
augroup END
```

**Comment by dylan-chong** [comment]
Thanks, you make some really good points.  i'll give it a try and see what i think

**Comment by dylan-chong** [comment]
I have tried using 

```
augroup custom_filemru
  autocmd!
  autocmd BufEnter * UpdateMru
  autocmd BufLeave * UpdateMru
augroup END
```

but oddly files sometimes don't appear in the mru. Files even disappear from the mru when switching between multiple buffers in the same window. Sometimes the most recent file is in the mru but not at the bottom as well. it's as if this plugin is receiving only half of the events

Any ideas on why this is happening?
