### ISSUE TITLE
Breaking on MacOS

### ISSUE THREAD

**Issue by PauloPhagula** [tweekmonster/fzf-filemru#8]
Hi,

I use this plugin on both MacOS and Linux. I've noticed that sometimes on MacOS it breaks as seen on the image below. I've never gotten this on Linux.

<img width="547" alt="screen shot 2018-10-15 at 22 11 45" src="https://user-images.githubusercontent.com/6130991/46975639-6e283c00-d0c7-11e8-91bc-20b501085f99.png">

I wonder if this is perhaps some misconfiguration or if is there something I can do to fix?

Thanks

**Comment by tweekmonster** [comment]
Thanks @dareenzo, this appears to be related to #4.  I think I understand this problem now since you specifically mentioned MacOS.  The script that generates the file list uses `echo -e` and it looks like the `-e` flag isn't POSIX and not available in the MacOS `echo` command.

This should print `git` in yellow in your MacOS terminal:

```sh
printf "\e[38;5;3mgit\e[m\n"
```

I'll update the script to use `printf` instead.

**Comment by tweekmonster** [comment]
This should now be fixed in d76b2ea

**Comment by PauloPhagula** [comment]
Tested and Confirmed. The change above fixed the issue. 
Thanks

**Comment by dylan-chong** [comment]
@dareenzo May i ask how you got this plugin to setup on mac os? On my setup it does not show the most recent files, just the list of files in the current directory

nnoremap <silent> <Leader>F :FilesMru --tiebreak=end<cr>

**Comment by dylan-chong** [comment]
@dareenzo May i ask how you got this plugin to setup on mac os? On my setup it does not show the most recent files, just the list of files in the current directory

nnoremap <silent> <Leader>F :FilesMru --tiebreak=end<cr>

**Comment by dylan-chong** [comment]
@dareenzo May i ask how you got this plugin to setup on mac os? On my setup it does not show the most recent files, just the list of files in the current directory

nnoremap <silent> <Leader>F :FilesMru --tiebreak=end<cr>

**Comment by PauloPhagula** [comment]
I got it like below, and I'm sharing between Linux and MacOS

```vim
nnoremap <c-p> :ProjectMru --tiebreak=end<CR>
let g:fzf_filemru_bufwrite = 1
let g:fzf_filemru_git_ls = 1
let g:fzf_filemru_ignore_submodule = 1
```

**Comment by dylan-chong** [comment]
Interesting. When i bring up the menu i get this which is just a list of all the project files without any of the most recent ones
![screen shot 2018-10-23 at 7 33 28 am](https://user-images.githubusercontent.com/17482349/47311340-f2fdf180-d695-11e8-81dc-4d74c8992210.png)

Just looking at the readme, tdid you have to set `XDG_CACHE_HOME `?

**Comment by PauloPhagula** [comment]
Now that you mention it, I checked again and you're right. I don't get the MRU either on Mac. I get it only on Linux.

I do have a file and a folder created at `~/.cache` related to MRU (fzf_filemru, fzf_mru), but I don't have the `XDG_CACHE_HOME` variable set.

Probably @tweekmonster can clarify more on the setup requirements.

**Comment by tweekmonster** [comment]
@dylan-chong @dareenzo The script will sort out the paths if that variable isn't set.  The actual problem is that POSIX awk doesn't support the `systime()` call https://github.com/tweekmonster/fzf-filemru/blob/master/bin/filemru.sh#L43
gawk supports `systime()`, so I made it a "requirement", but I didn't really like it at the time.  I recently noticed the issue myself since I upgraded my laptop but didn't install gawk.

This should fix the issue:

```diff
diff --git a/bin/filemru.sh b/bin/filemru.sh
index 541437d..3914b98 100755
--- a/bin/filemru.sh
+++ b/bin/filemru.sh
@@ -42,3 +42,3 @@ update_mru() {
     BEGIN {
-      ts = systime()
+      ts = '$(date +%s)'
       ts -= (ts % 120)
```

The problem with this is that the POSIX `date` program doesn't support the `+%s` format.  It works with GNU `date` on Linux and in MacOS's non-GNU `date`, so that's probably enough for now since I'm still unable to find a fast and reliable way to get a unix timestamp from bash using only POSIX programs.
